black-knife:
  uuid: black-knife
  name: Black Knife
  material: WOODEN_SWORD
  physicDamage: 5
  magicDamage: 0
  durability: 10000
  attackSpeed: 8
  attackRange: 1.5
fire-sword:
  uuid: fire-sword
  name: Fire Sword
  material: WOODEN_SWORD
  physicDamage: 8
  magicDamage: 2
  durability: 8000
  attackSpeed: -100
  attackRange: 2